version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres # Use service name defined in this file
      KC_DB_URL_DATABASE: postgres # Example value for Keycloak database name
      KC_DB_USERNAME: postgres # Example value for Keycloak database user
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD:
      KEYCLOAK_ADMIN: admin # Example value for Keycloak admin username
      KEYCLOAK_ADMIN_PASSWORD: admin # Example value for Keycloak admin password
    command:
      - "start-dev --http-port=8082"
    ports:
      - 8082:8082
    depends_on:
      - postgres
#  app:
#    build:
#      context: ./
#      dockerfile: dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
#      - postgres
#      - mongo